site_name: RanCat Docs
site_author: Matthew Egan (github/mattjegan)
repo_url: https://github.com/mattjegan/rancat
repo_name: mattjegan/rancat
pages:
- Home: index.md
- The RanCat Object: RanCat.md
- Contributing: contributing.md
- CHANGELOG: CHANGELOG.md
- LICENSE: LICENSE.md
theme: readthedocs
